### ISSUE TITLE
How to implement reset() function for Procgen environments?

### ISSUE THREAD

**Issue by hasanferit** [openai/procgen#40] opened 2020-05-04 18:07 UTC
In my use case, I investigate the behaviors of agents on custom action policies (i.e. actions determined by me, not the agent). For each run of an action policy I have to create the environment from scratch and it takes almost 2/3 of all my process. 

I am assuming that  if environment's reset() function would be implemented then it would be much faster. Is there is specific reason for not implementing it? If no, can you help me implementing I?

**Comment by christopherhesse** [comment] 2020-05-04 22:07
I measured 177 microseconds for a step of coinrun and 20 milliseconds for re-creating the environment.   What kind of speeds are you getting?  How often are you resetting the environment?

**Comment by hasanferit** [comment] 2020-05-05 11:05
After a few optimizations my [line profiler](https://github.com/pyutils/line_profiler#bugs-and-such) gives me the following result:
![Screen Shot 2020-05-05 at 12 43 15 PM](https://user-images.githubusercontent.com/2608508/81058722-4ed24900-8ecf-11ea-85f9-eef7e7647718.png)

Currently, creating environment for every run takes 1/3 of my whole process.
`create_environment()` function consists of the following two lines:

    env = ProcgenEnv(num_envs=1, env_name=self.env_name, num_levels=self.num_levels, start_level=self.start_level, distribution_mode=self.distribution_mode)
    env = VecExtractDictObs(env, "rgb")

And `run()` function is nothing but playing the game with a custom action policy for some number of steps.

This is some other point but, actually, I don't understand why I get spurious rewards if I don't create the environment from scratch for each custom action policy. I was thinking that setting the first observation to level's initial observation would work.

**Comment by christopherhesse** [comment] 2020-05-05 17:20
I don't understand the spurious rewards thing, do you have a short example script that demonstrates the issue?

**Comment by hasanferit** [comment] 2020-05-06 14:28
I figured out the reason for spurious rewards while I am working on an example. Apparently, the environment keeps a counter for each step taken at the background end yields 0 reward when it is 500 in maze game. If I don't create the environment from scratch for each run, it can give me 0 reward in some unexpected situation.

I resolved my issue in some other way, currently I don't need reset() function. But I believe, it would be good to have it for future references.

**Comment by christopherhesse** [comment] 2020-05-15 00:18
Is your version of procgen installed from source?

**Comment by christopherhesse** [comment] 2020-05-15 05:15
The spurious rewards thing sounds like a bug, is that a bug in procgen?

**Comment by hasanferit** [comment] 2020-05-17 12:45
Below, I explained a scenario. I consider a maze level that can be generated with `num_levels=1` and `start_level=137`. Its original initial state can be seen [here](https://drive.google.com/file/d/190hZDriUDmeZvN359cIyqnpWpkLKNPPh/view?usp=sharing).

I create a custom action policy as follows: [5, 5, 8, 7, 6, 6, 7, 7, 3, 7, 3, 5, 1]. This action policy brings the agent to a particular state from the initial state then agent continues playing from that state. The corresponding code for running the game is below:

```
def run(prefix):
  obs = initial_obs
  while True:
    if idx < len(prefix):
      act = prefix[idx]
    else:
      act = self.model.step(obs)
    obs, rew, done, info = self.env.step(act)
    if done: return
```
Here, `initial_obs` is determined just after the environment created with `env.reset()`.
But before running game I call the following function:

```
def get_last_observation(self, prefix):
  obs = None
  for act in prefix: obs, _, _, _ = self.env.step(act)
  return obs.flatten()
```

I use the returned observation for a separate analysis. Then, I run the game, but the agent starts in a position different from the `initial_obs` as seen [here](https://drive.google.com/file/d/1FXfYPvTfpH1qxm7zRf71PdyUO1J6APw-/view?usp=sharing).
As one can see, the initial state in this case corresponds to the state led by the custom action policy. But note that I make this assignment `obs = initial_obs` before running the game. Thus, this strange initial state is the cause for the spurious rewards.

**Comment by christopherhesse** [comment] 2020-05-17 21:44
I ran the following script but the initial obs always appears to be the same, as well as the last obs:

```import gym
import imageio


def get_last_observation(env, prefix):
  obs = None
  for act in prefix:
      obs, _, _, _ = env.step(act)
  return obs

env = gym.make("procgen:procgen-maze-v0", num_levels=1, start_level=137)
initial_obs = env.reset()
imageio.imsave("initial.png", initial_obs)
prefix = [5, 5, 8, 7, 6, 6, 7, 7, 3, 7, 3, 5, 1]
last_obs = get_last_observation(env, prefix)
imageio.imsave("last.png", last_obs)

env = gym.make("procgen:procgen-maze-v0", num_levels=1, start_level=137)
initial_obs = env.reset()
imageio.imsave("initial2.png", initial_obs)
last_obs = get_last_observation(env, prefix)
imageio.imsave("last2.png", last_obs)```

**Comment by christopherhesse** [comment] 2020-05-17 21:44
Do you have a script that reproduces the issue?

**Comment by hasanferit** [comment] 2020-05-17 22:29
I attached a script. 
[maze_test.txt](https://github.com/openai/procgen/files/4641181/maze_test.txt)

Actually, I think this is neither a bug nor an issue. This is just a demonstration of my need for `env.reset()`. Previously, for some silly reason I thought that the assignment in 25th line would bring the agent to the original initial state.

**Comment by christopherhesse** [comment] 2020-05-18 00:08
Okay, we're unlikely to add a `reset()` method any time soon, though you are free to add that in your own fork of course.  I'll leave this open until the next release, which will have slightly faster environment creation.

**Comment by hasanferit** [comment] 2020-05-25 21:24
According to the check [here](https://github.com/openai/procgen/blob/master/procgen/src/game.cpp#L119), apparently, one can force the environment to be reseted by sending an action **-1** .

**Comment by christopherhesse** [comment] 2020-05-25 23:28
Good find, @kcobbe is there any downside to resetting using that?

**Comment by christopherhesse** [comment] 2020-06-03 16:36
Closing this since it looks like there already is a way to reset the environment, and also environment creation should be faster now.

**Closed by christopherhesse** 2020-06-03 16:36 UTC
